### ISSUE TITLE
Function pkg_names shows a package name for a non-existent package

### ISSUE THREAD

**Issue by cFire** [spk/ruby-apt-pkg#3]
I'm not sure (yet) in which cases this happens, but I've found an example with "exiftool" which is not a package that exists, yet it is provided as the only matching package by `pkg_search`.
```
[ 06:50 coolfire@absolute-unit manager2-cli ]
$ apt search exiftool
Sorting... Done
Full Text Search... Done
forensics-extra/bionic,bionic,now 1.13 all [installed]
  Forensics Environment - extra console components (metapackage)

libimage-exiftool-perl/bionic,bionic,now 10.80-1 all [installed]
  library and program to read and write meta information in multimedia files

ruby-mini-exiftool/bionic,bionic,now 2.9.0-1 all [installed,automatic]
  wrapper for exiftool command-line


[ 06:50 coolfire@absolute-unit manager2-cli ]
$ irb
irb(main):001:0> require 'debian/apt_pkg'
=> true
irb(main):002:0> Debian::AptPkg.init
=> nil
irb(main):003:0> Debian::AptPkg::PkgCache.update
=> false
irb(main):004:0> Debian::AptPkg::PkgCache.pkg_names('exiftool')
=> ["exiftool"]
irb(main):005:0> 
```

**Comment by spk** [comment]
I don't remember why I exposed this method since I don't find any equivalent on python-apt... From my quick lookup this look to come from the `Provides` from `libimage-exiftool-perl` so it match on the cache this name. This works for package like `archfs` too. I think I'm going to remove this method when I've implemented a proper search method since this cause confusion cf #2

**Comment by spk** [comment]
I've started the listing of packages on cache in https://github.com/spk/ruby-apt-pkg/commit/0d76d71eec2539be67b68466ca91f72ea224e4f7 and deprecated the pkg_names method its going to be removed in 0.6.0

**Comment by spk** [comment]
Package listing is released in https://github.com/spk/ruby-apt-pkg/releases/tag/v0.5.0
